#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */

/* Variables and functions */
#define  ERROR_COMMON_CMD 238 
#define  ERROR_COMMON_INPUT_INIT 237 
#define  ERROR_COMMON_INPUT_PATH 236 
#define  ERROR_COMMON_OUTPUT_INIT 235 
#define  ERROR_COMMON_OUTPUT_PATH 234 
#define  ERROR_COMMON_PARAMETER 233 
#define  ERROR_COMMON_SETFILE_ADJUST 232 
#define  ERROR_COMMON_SETFILE_INDEX 231 
#define  ERROR_COMMON_SETFILE_LOAD 230 
#define  ERROR_CONTROL_BYPASS 229 
#define  ERROR_DMA_INPUT_BIT_WIDTH 228 
#define  ERROR_DMA_INPUT_FORMAT 227 
#define  ERROR_DMA_INPUT_HEIGHT 226 
#define  ERROR_DMA_INPUT_ORDER 225 
#define  ERROR_DMA_INPUT_PLANE 224 
#define  ERROR_DMA_INPUT_WIDTH 223 
#define  ERROR_DMA_OUTPUT_BIT_WIDTH 222 
#define  ERROR_DMA_OUTPUT_FORMAT 221 
#define  ERROR_DMA_OUTPUT_HEIGHT 220 
#define  ERROR_DMA_OUTPUT_ORDER 219 
#define  ERROR_DMA_OUTPUT_PLANE 218 
#define  ERROR_DMA_OUTPUT_WIDTH 217 
#define  ERROR_FD_CONFIG_BLINK_MODE_INVALID 216 
#define  ERROR_FD_CONFIG_EYES_DETECT_INVALID 215 
#define  ERROR_FD_CONFIG_MAX_NUMBER_INVALID 214 
#define  ERROR_FD_CONFIG_MAX_NUMBER_STATE 213 
#define  ERROR_FD_CONFIG_MOUTH_DETECT_INVALID 212 
#define  ERROR_FD_CONFIG_ORIENTATION_INVALID 211 
#define  ERROR_FD_CONFIG_ORIENTATION_STATE 210 
#define  ERROR_FD_CONFIG_ORIENTATION_VALUE_INVALID 209 
#define  ERROR_FD_CONFIG_ROLL_ANGLE_INVALID 208 
#define  ERROR_FD_CONFIG_ROLL_ANGLE_STATE 207 
#define  ERROR_FD_CONFIG_SMILE_MODE_INVALID 206 
#define  ERROR_FD_CONFIG_YAW_ANGLE_INVALID 205 
#define  ERROR_FD_CONFIG_YAW_ANGLE_STATE 204 
#define  ERROR_FD_MODE 203 
#define  ERROR_FD_RESULT 202 
#define  ERROR_ISP_AF_BUSY 201 
#define  ERROR_ISP_AF_INVALID_COMMAND 200 
#define  ERROR_ISP_AF_INVALID_MODE 199 
#define  ERROR_OTF_INPUT_BIT_WIDTH 198 
#define  ERROR_OTF_INPUT_FORMAT 197 
#define  ERROR_OTF_INPUT_HEIGHT 196 
#define  ERROR_OTF_INPUT_WIDTH 195 
#define  ERROR_OTF_OUTPUT_BIT_WIDTH 194 
#define  ERROR_OTF_OUTPUT_FORMAT 193 
#define  ERROR_OTF_OUTPUT_HEIGHT 192 
#define  ERROR_OTF_OUTPUT_WIDTH 191 
#define  ERROR_SENSOR_ACTURATOR_INIT_FAIL 190 
#define  ERROR_SENSOR_I2C_FAIL 189 
#define  ERROR_SENSOR_INVALID_AF_POS 188 
#define  ERROR_SENSOR_INVALID_EXPOSURETIME 187 
#define  ERROR_SENSOR_INVALID_FRAMERATE 186 
#define  ERROR_SENSOR_INVALID_SETTING 185 
#define  ERROR_SENSOR_INVALID_SIZE 184 
#define  ERROR_SENSOR_UNSUPPORT_AF 183 
#define  ERROR_SENSOR_UNSUPPORT_FUNC 182 
#define  ERROR_SENSOR_UNSUPPORT_PERI 181 
#define  IS_ERROR_BUSY 180 
#define  IS_ERROR_DIS_FRAME_END_NOT_DONE 179 
#define  IS_ERROR_DRC_ABSENT_INPUT 178 
#define  IS_ERROR_DRC_ABSENT_OUTPUT 177 
#define  IS_ERROR_DRC_BITWIDTH_MISMATCH 176 
#define  IS_ERROR_DRC_FORMAT_MISMATCH 175 
#define  IS_ERROR_DRC_FRAME_END_NOT_DONE 174 
#define  IS_ERROR_DRC_FRAME_END_TIME_OUT 173 
#define  IS_ERROR_DRC_HEIGHT_MISMATCH 172 
#define  IS_ERROR_DRC_MSG_FAIL 171 
#define  IS_ERROR_DRC_MULTIPLE_INPUT 170 
#define  IS_ERROR_DRC_NONADJACENT_INPUT 169 
#define  IS_ERROR_DRC_NONADJACENT_OUTPUT 168 
#define  IS_ERROR_DRC_PWRDN_FAIL 167 
#define  IS_ERROR_DRC_WIDTH_MISMATCH 166 
#define  IS_ERROR_ENTRY_MSG_THREAD_DOWN 165 
#define  IS_ERROR_FD_ABSENT_INPUT 164 
#define  IS_ERROR_FD_MULTIPLE_INPUT 163 
#define  IS_ERROR_FD_NONADJACENT_INPUT 162 
#define  IS_ERROR_FD_PWRDN_FAIL 161 
#define  IS_ERROR_INVALID_COMMAND 160 
#define  IS_ERROR_INVALID_MAGIC_NUMBER 159 
#define  IS_ERROR_INVALID_MODE_CHANGE 158 
#define  IS_ERROR_INVALID_PATH 157 
#define  IS_ERROR_INVALID_SCENARIO 156 
#define  IS_ERROR_INVALID_SENSORID 155 
#define  IS_ERROR_INVALID_SETFILE_HDR 154 
#define  IS_ERROR_ISP_ABSENT_INPUT 153 
#define  IS_ERROR_ISP_ABSENT_OUTPUT 152 
#define  IS_ERROR_ISP_BITWIDTH_MISMATCH 151 
#define  IS_ERROR_ISP_FORMAT_MISMATCH 150 
#define  IS_ERROR_ISP_FRAME_END_NOT_DONE 149 
#define  IS_ERROR_ISP_FRAME_END_TIME_OUT 148 
#define  IS_ERROR_ISP_HEIGHT_MISMATCH 147 
#define  IS_ERROR_ISP_MSG_FAIL 146 
#define  IS_ERROR_ISP_MULTIPLE_INPUT 145 
#define  IS_ERROR_ISP_NONADJACENT_OUTPUT 144 
#define  IS_ERROR_ISP_PWRDN_FAIL 143 
#define  IS_ERROR_ISP_WIDTH_MISMATCH 142 
#define  IS_ERROR_LHFD_FRAME_END_TIME_OUT 141 
#define  IS_ERROR_LHFD_MSG_FAIL 140 
#define  IS_ERROR_NO_MSG_IS_RECEIVED 139 
#define  IS_ERROR_ODC_FRAME_END_NOT_DONE 138 
#define  IS_ERROR_OPEN_SENSOR_FAIL 137 
#define  IS_ERROR_REQUEST_FAIL 136 
#define  IS_ERROR_SCALERC_FRAME_END_NOT_DONE 135 
#define  IS_ERROR_SCALERP_FRAME_END_NOT_DONE 134 
#define  IS_ERROR_SENSOR_MSG_FAIL 133 
#define  IS_ERROR_SENSOR_PWRDN_FAIL 132 
#define  IS_ERROR_SET_PARAMETER 131 
#define  IS_ERROR_TDNR_FRAME_END_NOT_DONE 130 
 unsigned int IS_ERROR_TIME_OUT_FLAG ; 
#define  IS_ERROR_UNKNOWN 129 
#define  IS_ERROR_WAIT_STREAM_OFF_NOT_DONE 128 

const char *fimc_is_param_strerr(unsigned int error)
{
	switch (error) {
	case ERROR_COMMON_CMD:
		return "ERROR_COMMON_CMD: Invalid Command";
	case ERROR_COMMON_PARAMETER:
		return "ERROR_COMMON_PARAMETER: Invalid Parameter";
	case ERROR_COMMON_SETFILE_LOAD:
		return "ERROR_COMMON_SETFILE_LOAD: Illegal Setfile Loading";
	case ERROR_COMMON_SETFILE_ADJUST:
		return "ERROR_COMMON_SETFILE_ADJUST: Setfile isn't adjusted";
	case ERROR_COMMON_SETFILE_INDEX:
		return "ERROR_COMMON_SETFILE_INDEX: Invalid setfile index";
	case ERROR_COMMON_INPUT_PATH:
		return "ERROR_COMMON_INPUT_PATH: Input path can be changed in ready state";
	case ERROR_COMMON_INPUT_INIT:
		return "ERROR_COMMON_INPUT_INIT: IP can not start if input path is not set";
	case ERROR_COMMON_OUTPUT_PATH:
		return "ERROR_COMMON_OUTPUT_PATH: Output path can be changed in ready state (stop)";
	case ERROR_COMMON_OUTPUT_INIT:
		return "ERROR_COMMON_OUTPUT_INIT: IP can not start if output path is not set";
	case ERROR_CONTROL_BYPASS:
		return "ERROR_CONTROL_BYPASS";
	case ERROR_OTF_INPUT_FORMAT:
		return "ERROR_OTF_INPUT_FORMAT: Invalid format  (DRC: YUV444, FD: YUV444, 422, 420)";
	case ERROR_OTF_INPUT_WIDTH:
		return "ERROR_OTF_INPUT_WIDTH: Invalid width (DRC: 128~8192, FD: 32~8190)";
	case ERROR_OTF_INPUT_HEIGHT:
		return "ERROR_OTF_INPUT_HEIGHT: Invalid bit-width (DRC: 8~12bits, FD: 8bit)";
	case ERROR_OTF_INPUT_BIT_WIDTH:
		return "ERROR_OTF_INPUT_BIT_WIDTH: Invalid bit-width (DRC: 8~12bits, FD: 8bit)";
	case ERROR_DMA_INPUT_WIDTH:
		return "ERROR_DMA_INPUT_WIDTH: Invalid width (DRC: 128~8192, FD: 32~8190)";
	case ERROR_DMA_INPUT_HEIGHT:
		return "ERROR_DMA_INPUT_HEIGHT: Invalid height (DRC: 64~8192, FD: 16~8190)";
	case ERROR_DMA_INPUT_FORMAT:
		return "ERROR_DMA_INPUT_FORMAT: Invalid format (DRC: YUV444 or YUV422, FD: YUV444,422,420)";
	case ERROR_DMA_INPUT_BIT_WIDTH:
		return "ERROR_DMA_INPUT_BIT_WIDTH: Invalid bit-width (DRC: 8~12bits, FD: 8bit)";
	case ERROR_DMA_INPUT_ORDER:
		return "ERROR_DMA_INPUT_ORDER: Invalid order(DRC: YYCbCr,YCbYCr,FD:NO,YYCbCr,YCbYCr,CbCr,CrCb)";
	case ERROR_DMA_INPUT_PLANE:
		return "ERROR_DMA_INPUT_PLANE: Invalid palne (DRC: 3, FD: 1, 2, 3)";
	case ERROR_OTF_OUTPUT_WIDTH:
		return "ERROR_OTF_OUTPUT_WIDTH: Invalid width (DRC: 128~8192)";
	case ERROR_OTF_OUTPUT_HEIGHT:
		return "ERROR_OTF_OUTPUT_HEIGHT: Invalid height (DRC: 64~8192)";
	case ERROR_OTF_OUTPUT_FORMAT:
		return "ERROR_OTF_OUTPUT_FORMAT: Invalid format (DRC: YUV444)";
	case ERROR_OTF_OUTPUT_BIT_WIDTH:
		return "ERROR_OTF_OUTPUT_BIT_WIDTH: Invalid bit-width (DRC: 8~12bits, FD: 8bit)";
	case ERROR_DMA_OUTPUT_WIDTH:
		return "ERROR_DMA_OUTPUT_WIDTH";
	case ERROR_DMA_OUTPUT_HEIGHT:
		return "ERROR_DMA_OUTPUT_HEIGHT";
	case ERROR_DMA_OUTPUT_FORMAT:
		return "ERROR_DMA_OUTPUT_FORMAT";
	case ERROR_DMA_OUTPUT_BIT_WIDTH:
		return "ERROR_DMA_OUTPUT_BIT_WIDTH";
	case ERROR_DMA_OUTPUT_PLANE:
		return "ERROR_DMA_OUTPUT_PLANE";
	case ERROR_DMA_OUTPUT_ORDER:
		return "ERROR_DMA_OUTPUT_ORDER";

	/* Sensor Error(100~199) */
	case ERROR_SENSOR_I2C_FAIL:
		return "ERROR_SENSOR_I2C_FAIL";
	case ERROR_SENSOR_INVALID_FRAMERATE:
		return "ERROR_SENSOR_INVALID_FRAMERATE";
	case ERROR_SENSOR_INVALID_EXPOSURETIME:
		return "ERROR_SENSOR_INVALID_EXPOSURETIME";
	case ERROR_SENSOR_INVALID_SIZE:
		return "ERROR_SENSOR_INVALID_SIZE";
	case ERROR_SENSOR_INVALID_SETTING:
		return "ERROR_SENSOR_INVALID_SETTING";
	case ERROR_SENSOR_ACTURATOR_INIT_FAIL:
		return "ERROR_SENSOR_ACTURATOR_INIT_FAIL";
	case ERROR_SENSOR_INVALID_AF_POS:
		return "ERROR_SENSOR_INVALID_AF_POS";
	case ERROR_SENSOR_UNSUPPORT_FUNC:
		return "ERROR_SENSOR_UNSUPPORT_FUNC";
	case ERROR_SENSOR_UNSUPPORT_PERI:
		return "ERROR_SENSOR_UNSUPPORT_PERI";
	case ERROR_SENSOR_UNSUPPORT_AF:
		return "ERROR_SENSOR_UNSUPPORT_AF";

	/* ISP Error (200~299) */
	case ERROR_ISP_AF_BUSY:
		return "ERROR_ISP_AF_BUSY";
	case ERROR_ISP_AF_INVALID_COMMAND:
		return "ERROR_ISP_AF_INVALID_COMMAND";
	case ERROR_ISP_AF_INVALID_MODE:
		return "ERROR_ISP_AF_INVALID_MODE";

	/* DRC Error (300~399) */
	/* FD Error  (400~499) */
	case ERROR_FD_CONFIG_MAX_NUMBER_STATE:
		return "ERROR_FD_CONFIG_MAX_NUMBER_STATE";
	case ERROR_FD_CONFIG_MAX_NUMBER_INVALID:
		return "ERROR_FD_CONFIG_MAX_NUMBER_INVALID";
	case ERROR_FD_CONFIG_YAW_ANGLE_STATE:
		return "ERROR_FD_CONFIG_YAW_ANGLE_STATE";
	case ERROR_FD_CONFIG_YAW_ANGLE_INVALID:
		return "ERROR_FD_CONFIG_YAW_ANGLE_INVALID\n";
	case ERROR_FD_CONFIG_ROLL_ANGLE_STATE:
		return "ERROR_FD_CONFIG_ROLL_ANGLE_STATE";
	case ERROR_FD_CONFIG_ROLL_ANGLE_INVALID:
		return "ERROR_FD_CONFIG_ROLL_ANGLE_INVALID";
	case ERROR_FD_CONFIG_SMILE_MODE_INVALID:
		return "ERROR_FD_CONFIG_SMILE_MODE_INVALID";
	case ERROR_FD_CONFIG_BLINK_MODE_INVALID:
		return "ERROR_FD_CONFIG_BLINK_MODE_INVALID";
	case ERROR_FD_CONFIG_EYES_DETECT_INVALID:
		return "ERROR_FD_CONFIG_EYES_DETECT_INVALID";
	case ERROR_FD_CONFIG_MOUTH_DETECT_INVALID:
		return "ERROR_FD_CONFIG_MOUTH_DETECT_INVALID";
	case ERROR_FD_CONFIG_ORIENTATION_STATE:
		return "ERROR_FD_CONFIG_ORIENTATION_STATE";
	case ERROR_FD_CONFIG_ORIENTATION_INVALID:
		return "ERROR_FD_CONFIG_ORIENTATION_INVALID";
	case ERROR_FD_CONFIG_ORIENTATION_VALUE_INVALID:
		return "ERROR_FD_CONFIG_ORIENTATION_VALUE_INVALID";
	case ERROR_FD_RESULT:
		return "ERROR_FD_RESULT";
	case ERROR_FD_MODE:
		return "ERROR_FD_MODE";
	default:
		return "Unknown";
	}
}

const char *fimc_is_strerr(unsigned int error)
{
	error &= ~IS_ERROR_TIME_OUT_FLAG;

	switch (error) {
	/* General */
	case IS_ERROR_INVALID_COMMAND:
		return "IS_ERROR_INVALID_COMMAND";
	case IS_ERROR_REQUEST_FAIL:
		return "IS_ERROR_REQUEST_FAIL";
	case IS_ERROR_INVALID_SCENARIO:
		return "IS_ERROR_INVALID_SCENARIO";
	case IS_ERROR_INVALID_SENSORID:
		return "IS_ERROR_INVALID_SENSORID";
	case IS_ERROR_INVALID_MODE_CHANGE:
		return "IS_ERROR_INVALID_MODE_CHANGE";
	case IS_ERROR_INVALID_MAGIC_NUMBER:
		return "IS_ERROR_INVALID_MAGIC_NUMBER";
	case IS_ERROR_INVALID_SETFILE_HDR:
		return "IS_ERROR_INVALID_SETFILE_HDR";
	case IS_ERROR_BUSY:
		return "IS_ERROR_BUSY";
	case IS_ERROR_SET_PARAMETER:
		return "IS_ERROR_SET_PARAMETER";
	case IS_ERROR_INVALID_PATH:
		return "IS_ERROR_INVALID_PATH";
	case IS_ERROR_OPEN_SENSOR_FAIL:
		return "IS_ERROR_OPEN_SENSOR_FAIL";
	case IS_ERROR_ENTRY_MSG_THREAD_DOWN:
		return "IS_ERROR_ENTRY_MSG_THREAD_DOWN";
	case IS_ERROR_ISP_FRAME_END_NOT_DONE:
		return "IS_ERROR_ISP_FRAME_END_NOT_DONE";
	case IS_ERROR_DRC_FRAME_END_NOT_DONE:
		return "IS_ERROR_DRC_FRAME_END_NOT_DONE";
	case IS_ERROR_SCALERC_FRAME_END_NOT_DONE:
		return "IS_ERROR_SCALERC_FRAME_END_NOT_DONE";
	case IS_ERROR_ODC_FRAME_END_NOT_DONE:
		return "IS_ERROR_ODC_FRAME_END_NOT_DONE";
	case IS_ERROR_DIS_FRAME_END_NOT_DONE:
		return "IS_ERROR_DIS_FRAME_END_NOT_DONE";
	case IS_ERROR_TDNR_FRAME_END_NOT_DONE:
		return "IS_ERROR_TDNR_FRAME_END_NOT_DONE";
	case IS_ERROR_SCALERP_FRAME_END_NOT_DONE:
		return "IS_ERROR_SCALERP_FRAME_END_NOT_DONE";
	case IS_ERROR_WAIT_STREAM_OFF_NOT_DONE:
		return "IS_ERROR_WAIT_STREAM_OFF_NOT_DONE";
	case IS_ERROR_NO_MSG_IS_RECEIVED:
		return "IS_ERROR_NO_MSG_IS_RECEIVED";
	case IS_ERROR_SENSOR_MSG_FAIL:
		return "IS_ERROR_SENSOR_MSG_FAIL";
	case IS_ERROR_ISP_MSG_FAIL:
		return "IS_ERROR_ISP_MSG_FAIL";
	case IS_ERROR_DRC_MSG_FAIL:
		return "IS_ERROR_DRC_MSG_FAIL";
	case IS_ERROR_LHFD_MSG_FAIL:
		return "IS_ERROR_LHFD_MSG_FAIL";
	case IS_ERROR_UNKNOWN:
		return "IS_ERROR_UNKNOWN";

	/* Sensor */
	case IS_ERROR_SENSOR_PWRDN_FAIL:
		return "IS_ERROR_SENSOR_PWRDN_FAIL";

	/* ISP */
	case IS_ERROR_ISP_PWRDN_FAIL:
		return "IS_ERROR_ISP_PWRDN_FAIL";
	case IS_ERROR_ISP_MULTIPLE_INPUT:
		return "IS_ERROR_ISP_MULTIPLE_INPUT";
	case IS_ERROR_ISP_ABSENT_INPUT:
		return "IS_ERROR_ISP_ABSENT_INPUT";
	case IS_ERROR_ISP_ABSENT_OUTPUT:
		return "IS_ERROR_ISP_ABSENT_OUTPUT";
	case IS_ERROR_ISP_NONADJACENT_OUTPUT:
		return "IS_ERROR_ISP_NONADJACENT_OUTPUT";
	case IS_ERROR_ISP_FORMAT_MISMATCH:
		return "IS_ERROR_ISP_FORMAT_MISMATCH";
	case IS_ERROR_ISP_WIDTH_MISMATCH:
		return "IS_ERROR_ISP_WIDTH_MISMATCH";
	case IS_ERROR_ISP_HEIGHT_MISMATCH:
		return "IS_ERROR_ISP_HEIGHT_MISMATCH";
	case IS_ERROR_ISP_BITWIDTH_MISMATCH:
		return "IS_ERROR_ISP_BITWIDTH_MISMATCH";
	case IS_ERROR_ISP_FRAME_END_TIME_OUT:
		return "IS_ERROR_ISP_FRAME_END_TIME_OUT";

	/* DRC */
	case IS_ERROR_DRC_PWRDN_FAIL:
		return "IS_ERROR_DRC_PWRDN_FAIL";
	case IS_ERROR_DRC_MULTIPLE_INPUT:
		return "IS_ERROR_DRC_MULTIPLE_INPUT";
	case IS_ERROR_DRC_ABSENT_INPUT:
		return "IS_ERROR_DRC_ABSENT_INPUT";
	case IS_ERROR_DRC_NONADJACENT_INPUT:
		return "IS_ERROR_DRC_NONADJACENT_INPUT";
	case IS_ERROR_DRC_ABSENT_OUTPUT:
		return "IS_ERROR_DRC_ABSENT_OUTPUT";
	case IS_ERROR_DRC_NONADJACENT_OUTPUT:
		return "IS_ERROR_DRC_NONADJACENT_OUTPUT";
	case IS_ERROR_DRC_FORMAT_MISMATCH:
		return "IS_ERROR_DRC_FORMAT_MISMATCH";
	case IS_ERROR_DRC_WIDTH_MISMATCH:
		return "IS_ERROR_DRC_WIDTH_MISMATCH";
	case IS_ERROR_DRC_HEIGHT_MISMATCH:
		return "IS_ERROR_DRC_HEIGHT_MISMATCH";
	case IS_ERROR_DRC_BITWIDTH_MISMATCH:
		return "IS_ERROR_DRC_BITWIDTH_MISMATCH";
	case IS_ERROR_DRC_FRAME_END_TIME_OUT:
		return "IS_ERROR_DRC_FRAME_END_TIME_OUT";

	/* FD */
	case IS_ERROR_FD_PWRDN_FAIL:
		return "IS_ERROR_FD_PWRDN_FAIL";
	case IS_ERROR_FD_MULTIPLE_INPUT:
		return "IS_ERROR_FD_MULTIPLE_INPUT";
	case IS_ERROR_FD_ABSENT_INPUT:
		return "IS_ERROR_FD_ABSENT_INPUT";
	case IS_ERROR_FD_NONADJACENT_INPUT:
		return "IS_ERROR_FD_NONADJACENT_INPUT";
	case IS_ERROR_LHFD_FRAME_END_TIME_OUT:
		return "IS_ERROR_LHFD_FRAME_END_TIME_OUT";
	default:
		return "Unknown";
	}
}

